# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trains", "0002_station_alter_train_destination_alter_train_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=64)),
                ("last", models.CharField(max_length=64)),
                (
                    "trains",
                    models.ManyToManyField(
                        blank=True, related_name="passengers", to="trains.train"
                    ),
                ),
                ("contacts", models.CharField(max_length=64)),
            ],
        ),
    ]
